In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [7]:
df = pd.read_csv('AirlineScrappedReview_Cleaned_seif_we_ibra#1.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2807 entries, 0 to 2806
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Passanger_Name   2807 non-null   object
 1   Route            2807 non-null   object
 2   Rating           2807 non-null   float64
 3   Verified         2807 non-null   object
 4   Review_title     2807 non-null   object
 5   Review_content   2807 non-null   object
 6   Traveller_Type   2807 non-null   object
 7   Class            2807 non-null   object
 8   Start_Location   2807 non-null   object
 9   End_Location     2807 non-null   object
 10  Layover_Route    484 non-null    object
 11  Start_Latitude   2747 non-null   float64
 12  Start_Longitude  2747 non-null   float64
 13  Start_Address    2807 non-null   object
 14  End_Latitude     2708 non-null   float64
 15  End_Longitude    2708 non-null   float64
 16  End_Address      2807 non-null   object
dtypes: float64(5), object(12)
memory usage: 372.9+ KB

In [9]:

df = df[df['Class'] != "Unknown"].reset_index(drop=True)
df = df[df['Traveller_Type'] != "Unknown"].reset_index(drop=True)
df = df[df['Traveller_Type'] != "Various"].reset_index(drop=True)

encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(df[['Class', 'Traveller_Type', 'Verified']])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(['Class', 'Traveller_Type', 'Verified']))

df = pd.concat([df.drop(['Class', 'Traveller_Type', 'Verified'], axis=1), one_hot_df], axis=1)

In [10]:
df = df.drop(['Start_Latitude', 'Start_Longitude', 'End_Latitude', 'End_Longitude', 'Verified_Not Verified'], axis=1)

In [11]:
df

,Passanger_Name,Route,Rating,Review_title,Review_content,Start_Location,End_Location,Layover_Route,Start_Address,End_Address,Class_Business Class,Class_Economy Class,Class_First Class,Class_Premium Economy,Traveller_Type_Business,Traveller_Type_Couple Leisure,Traveller_Type_Family Leisure,Traveller_Type_Solo Leisure,Verified_Trip Verified
0,Paige Boet,New Orleans to London,1.0,The airline lost my luggage,The airline lost my luggage and was absolutely...,New Orleans,London,NaN,"New Orleans, Orleans Parish, Louisiana, United...","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1,S Layne,London to Amman,1.0,fully refunded by our travel insurance,"We booked on the BA website, round trip flight...",London,Amman,NaN,"London, Greater London, England, United Kingdom","عمان, ناحية عمان, لواء قصبة عمان, عمان, 11110,...",1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,E Lanewoski,Heathrow to Bodrum,2.0,no boarding drinks provided,"First time flying with BA business class, neve...",London Heathrow,Bodrum,NaN,"London Heathrow Airport, The Beacon Roundabout...","Bodrum, Muğla, Ege Bölgesi, Türkiye",1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,Joel Burman,Amman to London,4.0,WiFi didn't work,You can buy sandwiches and crisps but don't ex...,Amman,London,NaN,"عمان, ناحية عمان, لواء قصبة عمان, عمان, 11110,...","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,R Vines,London City to Ibiza,7.0,stick with economy,This is a two-for-one review covering economy ...,London City,Ibiza,NaN,"London City Airport, Connaught Road, Silvertow...","Eivissa, Illes Balears, España",1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2798,Sasha Guignard,Kiev to London,8.0,British Airways customer review,Flew from Kiev to London on their Airbus 319 i...,Kiev,London,NaN,"Київ, Україна","London, Greater London, England, United Kingdom",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2799,D Ross,London-Vancouver,7.0,British Airways customer review,LHR to YVR return. Hard earned Avios points tr...,London,Vancouver,NaN,"London, Greater London, England, United Kingdom","Vancouver, Metro Vancouver Regional District, ...",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2800,J Brown,LHR-ORD,5.0,British Airways customer review,Club World from LHR-ORD. Busy flight on the ag...,London Heathrow,"Chicago (IL), O'Hare International Airport",NaN,"London Heathrow Airport, The Beacon Roundabout...","O'Hare International Airport, 10000, West Higg...",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2801,Kevin Barrance,BOM-LHR,3.0,British Airways customer review,This review refers to a return trip from India...,Bombay (Mumbai) - Chhatrapati Shivaji Internat...,London Heathrow,NaN,Chhatrapati Shivaji Maharaj International Airp...,"London Heathrow Airport, Northern Perimeter Ro...",0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2802,Kevin Barrance,LHR-BOM,7.0,British Airways customer review,This review concerns LHR-BOM in Business Class...,London Heathrow,Bombay (Mumbai) - Chhatrapati Shivaji Internat...,NaN,"London Heathrow Airport, The Beacon Roundabout...",Chhatrapati Shivaji Maharaj International Airp...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [12]:
# Add the "Satisfied" column
df['Satisfied'] = (df['Rating'] >= 5).astype(int)

# Verify the new column
print("Satisfied column added!")
print("\nValue counts:")
print(df['Satisfied'].value_counts())

print("\nBreakdown by Rating:")
print(df.groupby('Rating')['Satisfied'].value_counts().unstack(fill_value=0))

print("\nSample rows:")
print(df[['Passanger_Name', 'Rating', 'Satisfied']].head(10))

# Check the dataframe info
print("\nUpdated DataFrame info:")
df.info()

Satisfied column added!

Value counts:
Satisfied
0    1586
1    1217
Name: count, dtype: int64

Breakdown by Rating:
Satisfied    0    1
Rating
1.0        707    0
2.0        341    0
3.0        343    0
4.0        195    0
5.0          0  174
6.0          0  135
7.0          0  221
8.0          0  267
9.0          0  207
10.0         0  213

Sample rows:
   Passanger_Name  Rating  Satisfied
0      Paige Boet     1.0          0
1         S Layne     1.0          0
2     E Lanewoski     2.0          0
3     Joel Burman     4.0          0
4         R Vines     7.0          1
5          M King     1.0          0
6          C Dean     1.0          0
7  Richard Hodges     7.0          1
8  Carol Willmore     1.0          0
9   Nadine Kohler     1.0          0

Updated DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2803 entries, 0 to 2802
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Passanger_Name                 2803 non-null   object
 1   Route                          2803 non-null   object
 2   Rating                         2803 non-null   float64
 3   Review_title                   2803 non-null   object
 4   Review_content                 2803 non-null   object
 5   Start_Location                 2803 non-null   object
 6   End_Location                   2803 non-null   object
 7   Layover_Route                  483 non-null    object
 8   Start_Address                  2803 non-null   object
 9   End_Address                    2803 non-null   object
 10  Class_Business Class           2803 non-null   float64
 11  Class_Economy Class            2803 non-null   float64
 12  Class_First Class              2803 non-null   float64
 13  Class_Premium Economy          2803 non-null   float64
 14  Traveller_Type_Business        2803 non-null   float64
 15  Traveller_Type_Couple Leisure  2803 non-null   float64
 16  Traveller_Type_Family Leisure  2803 non-null   float64
 17  Traveller_Type_Solo Leisure    2803 non-null   float64
 18  Verified_Trip Verified         2803 non-null   float64
 19  Satisfied                      2803 non-null   int64
dtypes: float64(10), int64(1), object(9)
memory usage: 438.1+ KB

In [13]:
df['Layover_Route'] = df['Layover_Route'].fillna('None')

In [14]:
df['Route'].value_counts()

Route
London to Johannesburg        16
London to Cape Town           15
Vancouver to London           13
BKK to LHR                    13
Johannesburg to London        13
                              ..
BOM-LHR                        1
LHR to Santorini               1
Seattle to Nice via London     1
Las Vegas to Venice            1
Lisbon to London               1
Name: count, Length: 1539, dtype: int64

In [83]:
df['Route'] = df['Route'].str.replace('Cape Town to ', 'CPT to ')
df['Route'] = df['Route'].str.replace('Johannesburg to ', 'JNB to ')
df['Route'] = df['Route'].str.replace(' to Johannesburg', ' to JNB')
df['Route'] = df['Route'].str.replace(' to Cape Town', ' to CPT')
df['Route'] = df['Route'].str.replace('London Heathrow to ', 'LHR to ')
df['Route'] = df['Route'].str.replace(' to London Heathrow', ' to LHR')
df['Route'] = df['Route'].str.replace('London Gatwick to ', 'LGW to ')
df['Route'] = df['Route'].str.replace(' to London Gatwick', ' to LGW')
df['Route'] = df['Route'].str.replace(' to Hong Kong', ' to HKG')
df['Route'] = df['Route'].str.replace('Hong Kong to ', ' HKG to')
df['Route'] = df['Route'].str.replace(' to San Francisco', ' to SFO')
df['Route'] = df['Route'].str.replace('San Francisco to ', ' SFO to')
df['Route'] = df['Route'].str.replace(' to Rotterdam', ' to RTM')
df['Route'] = df['Route'].str.replace('Rotterdam to ', ' RTM to')
df['Route'] = df['Route'].str.replace(' to Muscat', ' to MCT')
df['Route'] = df['Route'].str.replace('Muscat to ', ' MCT to')
df['Route'] = df['Route'].str.replace(' to Lisbon', ' to LIS')
df['Route'] = df['Route'].str.replace('Lisbon to ', ' LIS to')
df['Route'] = df['Route'].str.replace(' to London-Heathrow', ' to LHR')
df['Route'] = df['Route'].str.replace('London-Heathrow to ', ' LHR to')
df['Route'] = df['Route'].str.replace(' via London-Heathrow', ' via LHR')
df['Route'] = df['Route'].str.replace(' via London Heathrow', ' via LHR')
df['Route'] = df['Route'].str.replace(' via Heathrow', ' via LHR')
df['Route'] = df['Route'].str.replace(' to Heathrow', ' to LHR')
df['Route'] = df['Route'].str.replace('Heathrow to ', 'LHR to')
df['Route'] = df['Route'].str.replace('to London UK (Heathrow)', 'LHR to')
df['Route'] = df['Route'].str.replace('Heathrow (London) to ', 'LHR to')
df['Route'] = df['Route'].str.replace('Ibiza to ', 'IBZ to ')
df['Route'] = df['Route'].str.replace(' to Ibiza', ' to IBZ')
df['Route'] = df['Route'].str.replace(' toIbiza', ' to IBZ')
df['Route'] = df['Route'].str.replace('Bodrum to ', 'BJV to ')
df['Route'] = df['Route'].str.replace(' to Bodrum', ' to BJV')
df['Route'] = df['Route'].str.replace(' toBodrum', ' to BJV')
df['Route'] = df['Route'].str.replace('Aberdeen to ', 'ABZ to ')
df['Route'] = df['Route'].str.replace(' to Aberdeen', ' to ABZ')
df['Route'] = df['Route'].str.replace('Tampa to ', 'TPA to ')
df['Route'] = df['Route'].str.replace(' to Tampa', ' to TPA')
df['Route'] = df['Route'].str.replace('Gatwick to ', 'LGW to ')
df['Route'] = df['Route'].str.replace(' to Gatwick', ' to LGW')
df['Route'] = df['Route'].str.replace('Islamabad to ', 'ISB to ')
df['Route'] = df['Route'].str.replace(' to Islamabad', ' to ISB')
df['Route'] = df['Route'].str.replace('Dallas Fort-Worth to ', 'DFW to ')
df['Route'] = df['Route'].str.replace('Dallas Ft Worth to ', 'DFW to ')
df['Route'] = df['Route'].str.replace('Dallas to ', 'DFW to ')
df['Route'] = df['Route'].str.replace(' to Dallas', ' to DFW')
df['Route'] = df['Route'].str.replace('Geneva to ', 'GVA to ')
df['Route'] = df['Route'].str.replace(' to Geneva', ' to GVA')
df['Route'] = df['Route'].str.replace('Barbados to ', 'BGI to ')
df['Route'] = df['Route'].str.replace(' to Barbados', ' to BGI')
df['Route'] = df['Route'].str.replace('Bridgetown to ', 'BGI to ')
df['Route'] = df['Route'].str.replace(' to Bridgetown', ' to BGI')
df['Route'] = df['Route'].str.replace(' to Genoa', ' to GOA')
df['Route'] = df['Route'].str.replace(' to Nice', ' to NCE')
df['Route'] = df['Route'].str.replace('Nice to DFW via London', 'NCE to DFW via London')
df['Route'] = df['Route'].str.replace('Nice to Kuwait via London', 'NCE to KWI via London')
df['Route'] = df['Route'].str.replace('Nice to LGW', 'NCE to LGW')
df['Route'] = df['Route'].str.replace('Nice to LHR', 'NCE to LHR')
df['Route'] = df['Route'].str.replace('Oakland to ', 'OAK to ')
df['Route'] = df['Route'].str.replace('Kuwait to ', 'KWI to ')
df['Route'] = df['Route'].str.replace(' to Geneva', ' to GVA')
df['Route'] = df['Route'].str.replace('Barbados to ', 'BGI to ')
df['Route'] = df['Route'].str.replace(' to Male', ' to MLE')
df['Route'] = df['Route'].str.replace('Male to ', 'MLE to ')
df['Route'] = df['Route'].str.replace(' to Malaga', ' to AGP')
df['Route'] = df['Route'].str.replace(' toMalaga', ' to AGP')
df['Route'] = df['Route'].str.replace('Malaga to ', 'AGP to ')
df['Route'] = df['Route'].str.replace(' to Newcastle', ' to NCL')
df['Route'] = df['Route'].str.replace('Newcastle to ', 'NCL to ')
df['Route'] = df['Route'].str.replace(' to Florence', ' to FLR')
df['Route'] = df['Route'].str.replace('-Florence', ' to FLR')
df['Route'] = df['Route'].str.replace('Florence to ', 'FLR to ')
df['Route'] = df['Route'].str.replace(' to Brindisi', ' to BDS')
df['Route'] = df['Route'].str.replace('Brindisi to ', 'BDS to ')
df['Route'] = df['Route'].str.replace(' to Gibraltar', ' to GIB')
df['Route'] = df['Route'].str.replace('Gibraltar to ', 'GIB to ')
df['Route'] = df['Route'].str.replace(' to Bangalore', ' to BLR')
df['Route'] = df['Route'].str.replace('Bangalore to ', 'BLR to ')
df['Route'] = df['Route'].str.replace(' to Amsterdam', ' to AMS')
df['Route'] = df['Route'].str.replace(' toAmsterdam', ' to AMS')
df['Route'] = df['Route'].str.replace('Amsterdam to ', 'AMS to ')
df['Route'] = df['Route'].str.replace(' to Prague', ' to PRG')
df['Route'] = df['Route'].str.replace('Prague to ', 'PRG to ')
df['Route'] = df['Route'].str.replace(' to Zagreb', ' to ZAG')
df['Route'] = df['Route'].str.replace('Zagreb to ', 'ZAG to ')
df['Route'] = df['Route'].str.replace(' to Tehran', ' to THR')
df['Route'] = df['Route'].str.replace('Tehran to ', 'THR to ')
df['Route'] = df['Route'].str.replace(' to Seville', ' to SVQ')
df['Route'] = df['Route'].str.replace('Seville to ', 'SVQ to ')
df['Route'] = df['Route'].str.replace(' to Belfast', ' to BFS')
df['Route'] = df['Route'].str.replace('Belfast to ', 'BFS to ')
df['Route'] = df['Route'].str.replace(' toBelfast', ' to BFS')
df['Route'] = df['Route'].str.replace('Belfast  to ', 'BFS to ')
df['Route'] = df['Route'].str.replace('Belfast City to ', 'BFS to ')
df['Route'] = df['Route'].str.replace('toJFK (New York City)', 'to JFK')
df['Route'] = df['Route'].str.replace('Edinburgh to ', 'EDI to ')
df['Route'] = df['Route'].str.replace('to Edinburgh', 'to EDI')
df['Route'] = df['Route'].str.replace('toEdinburgh', 'to EDI')
df['Route'] = df['Route'].str.replace(' to Riyadh', 'to RUH')
df['Route'] = df['Route'].str.replace('Riyadh to', 'RUH to ')
df['Route'] = df['Route'].str.replace('Santorini to ', 'JTR to ')
df['Route'] = df['Route'].str.replace(' to Santorini', ' to JTR')
df['Route'] = df['Route'].str.replace(' toSantorini', ' to JTR')
df['Route'] = df['Route'].str.replace(' to Murcia', ' to RMU')
df['Route'] = df['Route'].str.replace('Manchester to ', 'MAN to ')
df['Route'] = df['Route'].str.replace('Manchester, UK to ', 'MAN to ')
df['Route'] = df['Route'].str.replace(' to Manchester', ' to MAN')
df['Route'] = df['Route'].str.replace(' toManchester', ' to MAN')
df['Route'] = df['Route'].str.replace('Helsinki to ', 'HEL to ')
df['Route'] = df['Route'].str.replace(' to Helsinki', ' to HEL')
df['Route'] = df['Route'].str.replace('Tokyo Narita to ', 'NRT to ')
df['Route'] = df['Route'].str.replace(' to Tokyo Narita', ' to NRT')
df['Route'] = df['Route'].str.replace('San Francisco to ', 'SFO to ')
df['Route'] = df['Route'].str.replace(' to San Francisco', ' to SFO')
df['Route'] = df['Route'].str.replace(' to San francisco', ' to SFO')
df['Route'] = df['Route'].str.replace(' to san Francisco', ' to SFO')
df['Route'] = df['Route'].str.replace(' to San Fran', ' to SFO')
df['Route'] = df['Route'].str.replace('Nairobi to ', 'NBO to ')
df['Route'] = df['Route'].str.replace(' to Nairobi', ' to NBO')
df['Route'] = df['Route'].str.replace('Jeddah to ', 'JED to ')
df['Route'] = df['Route'].str.replace(' to Jeddah', ' to JED')
df['Route'] = df['Route'].str.replace('Houston to ', 'IAH to ')
df['Route'] = df['Route'].str.replace(' to Houston', ' to IAH')
df['Route'] = df['Route'].str.replace(' toHouston', ' to IAH')
df['Route'] = df['Route'].str.replace(' to Lyon', ' to LYS')
df['Route'] = df['Route'].str.replace(' toLyon', ' to LYS')
df['Route'] = df['Route'].str.replace('Lyon to ', 'LYS to ')
df['Route'] = df['Route'].str.replace('Seoul to ', 'ICN to ')
df['Route'] = df['Route'].str.replace(' to Seoul', ' to ICN')
df['Route'] = df['Route'].str.replace('Vienna to ', 'VIE to ')
df['Route'] = df['Route'].str.replace(' to Vienna', ' to VIE')
df['Route'] = df['Route'].str.replace(' toVienna', ' to VIE')
df['Route'] = df['Route'].str.replace('Bermuda to ', 'BDA to ')
df['Route'] = df['Route'].str.replace(' to Bermuda', ' to BDA')
df['Route'] = df['Route'].str.replace('Marseille to ', 'MRS to ')
df['Route'] = df['Route'].str.replace(' to Marseille', ' to MRS')
df['Route'] = df['Route'].str.replace(' toMarseille', ' to MRS')
df['Route'] = df['Route'].str.replace('London to CPT', 'LHR to CPT')
df['Route'] = df['Route'].str.replace('London to JNB', 'LHR to JNB')
df['Route'] = df['Route'].str.replace('Los Angeles to London', 'LAX to LHR')
df['Route'] = df['Route'].str.replace('JNB to London', 'JNB to LHR')
df['Route'] = df['Route'].str.replace('London to Athens', 'LHR to ATH')
df['Route'] = df['Route'].str.replace('HKG toLondon', 'HKG to LHR')
df['Route'] = df['Route'].str.replace('SFO toLondon', 'SFO to LHR')
df['Route'] = df['Route'].str.replace('Vancouver to London', 'YVR to LHR')
df['Route'] = df['Route'].str.replace('CPT to London', 'CPT to LHR')
df['Route'] = df['Route'].str.replace('CPT to London', 'CPT to LHR')
df['Route'] = df['Route'].str.replace('CPT to London', 'CPT to LHR')
df['Route'] = df['Route'].str.replace('London to Toronto', 'LHR to YYZ')
df['Route'] = df['Route'].str.replace('Singapore to London', 'SIN to LHR')
df['Route'] = df['Route'].str.replace('London to HKG', 'LHR to HKG')
df['Route'] = df['Route'].str.replace('Faro to ', 'FAO to ')
df['Route'] = df['Route'].str.replace(' to Faro', ' to FAO')
df['Route'] = df['Route'].str.replace(' toFaro', ' to FAO')
df['Route'] = df['Route'].str.replace('Shannon', 'SNN')
df['Route'] = df['Route'].str.replace('Hamburg to ', 'HAM to ')
df['Route'] = df['Route'].str.replace(' to Hamburg', ' to HAM')
df['Route'] = df['Route'].str.replace('Calgary to ', 'CYY to ')
df['Route'] = df['Route'].str.replace(' to Calgary', ' to CYY')
df['Route'] = df['Route'].str.replace('Zurich to ', 'ZRH to ')
df['Route'] = df['Route'].str.replace(' to Zurich', ' to ZRH')
df['Route'] = df['Route'].str.replace(' toZurich', ' to ZRH')
df['Route'] = df['Route'].str.replace('Dublin to ', 'DUB to ')
df['Route'] = df['Route'].str.replace(' to Dublin', ' to DUB')
df['Route'] = df['Route'].str.replace('Durban to ', 'DUR to ')
df['Route'] = df['Route'].str.replace(' to Durban', ' to DUR')
df['Route'] = df['Route'].str.replace('London to ', 'LHR to ')
df['Route'] = df['Route'].str.replace(' to London', ' to LHR')

df['Route'] = df['Route'].str.replace('Istanbul to ', 'IST to ')
df['Route'] = df['Route'].str.replace(' to Istanbul', ' to IST')
df['Route'] = df['Route'].str.replace('Stockholm to ', 'ARN to ')
df['Route'] = df['Route'].str.replace(' to Stockholm', ' to ARN')
df['Route'] = df['Route'].str.replace('Arlanda Stockholm to ', 'ARN to ')
df['Route'] = df['Route'].str.replace(' to Arlanda Stockholm', ' to ARN')
df['Route'] = df['Route'].str.replace('Stockholm Arlanda to ', 'ARN to ')
df['Route'] = df['Route'].str.replace(' to Stockholm Arlanda', ' to ARN')
df['Route'] = df['Route'].str.replace('Bangkok to ', 'BKK to ')
df['Route'] = df['Route'].str.replace(' to Bangkok', ' to BKK')
df['Route'] = df['Route'].str.replace(' toBangkok', ' to BKK')
df['Route'] = df['Route'].str.replace('Madrid to ', 'MAD to ')
df['Route'] = df['Route'].str.replace(' to Madrid', ' to MAD')
df['Route'] = df['Route'].str.replace('Berlin to ', 'TXL to ')
df['Route'] = df['Route'].str.replace(' to Berlin', ' to TXL')
df['Route'] = df['Route'].str.replace('Berlin Tegel to ', 'TXL to ')
df['Route'] = df['Route'].str.replace('Sydney to ', 'SYD to ')
df['Route'] = df['Route'].str.replace(' to Sydney', ' to SYD')
df['Route'] = df['Route'].str.replace('Cancun to ', 'CUN to ')
df['Route'] = df['Route'].str.replace(' to Cancun', ' to CUN')
df['Route'] = df['Route'].str.replace(' toCancun', ' to CUN')
df['Route'] = df['Route'].str.replace('Miami to ', 'MIA to ')
df['Route'] = df['Route'].str.replace(' to Miami', ' to MIA')
df['Route'] = df['Route'].str.replace(' toMiami', ' to MIA')
df['Route'] = df['Route'].str.replace('Sofia to ', 'SOF to ')
df['Route'] = df['Route'].str.replace(' to Sofia', ' to SOF')
df['Route'] = df['Route'].str.replace('Delhi to ', 'DEL to ')
df['Route'] = df['Route'].str.replace(' to Delhi', ' to DEL')
df['Route'] = df['Route'].str.replace(' to Delhi Airport', ' to DEL')
df['Route'] = df['Route'].str.replace(' to New Delhi', ' to DEL')
df['Route'] = df['Route'].str.replace(' to Frankfurt', ' to FRA')
df['Route'] = df['Route'].str.replace('Frankfurt to ', 'FRA to ')
df['Route'] = df['Route'].str.replace(' to Glasgow', ' to GLA')
df['Route'] = df['Route'].str.replace('Glasgow to ', 'GLA to ')
df['Route'] = df['Route'].str.replace(' toGlasgow', ' to GLA')
df['Route'] = df['Route'].str.replace(' to Antigua', ' to ANU')
df['Route'] = df['Route'].str.replace('Antigua to ', 'ANU to ')
df['Route'] = df['Route'].str.replace(' to St Lucia', ' to UVF')
df['Route'] = df['Route'].str.replace('St Lucia to ', 'UVF to ')

In [80]:
with pd.option_context('display.max_rows', None):
    display(df['Route'].value_counts())

Route
LHR to JNB                                  27
LHR to CPT                                  25
LHR to BKK                                  25
LHR to HKG                                  24
BKK to LHR                                  23
LHR to MIA                                  22
CPT to LHR                                  21
JNB to LHR                                  20
LHR to Dubai                                18
MIA to LHR                                  18
YVR to LHR                                  17
LGW to BGI                                  17
LHR to IST                                  16
MAD to LHR                                  16
LHR to SFO                                  16
LHR to ATH                                  16
LHR to YYZ                                  15
AMS to LHR                                  15
SIN to LHR                                  15
LHR to AMS                                  14
LHR to New York JFK                         14
LHR to EDI                                  14
Rome to LHR                                 13
Chicago to LHR                              13
LHR to MAD                                  12
JFK to LHR                                  12
LHR to Los Angeles                          12
IST to LHR                                  12
Dubai to LHR                                12
LHR to Vancouver                            12
Toronto to LHR                              12
 HKG to LHR                                 11
LGW to CUN                                  11
LHR to DUB                                  11
LHR to Singapore                            11
ZRH to LHR                                  11
LAX to LHR                                  11
LHR to Larnaca                              10
LHR to DEL                                  10
LHR to GLA                                  10
LHR to JFK                                  10
LHR to BFS                                  10
LHR to Chicago                               9
HKG to LHR                                   9
LHR to AGP                                   9
DUB to LHR                                   9
LHR to GVA                                   9
 SFO to LHR                                  9
LHR to Boston                                9
LHR to SOF                                   9
TXL to LHR                                   9
LHR to DXB                                   8
FRA to LHR                                   8
ARN to LHR                                   8
LHR to MAN                                   8
LHR to SIN                                   8
New York to LHR                              8
LHR to New York                              8
SYD to LHR via Singapore                     8
LHR to LIS                                   8
LHR to VIE                                   8
LHR to Rome                                  8
Athens to LHR                                8
LHR to Brussels                              7
LHR to Las Vegas                             7
LHR to NCE                                   7
BFS to LHR                                   7
LHR to KUL                                   7
ATH to LHR                                   7
LHR to ARN                                   7
LHR to ZRH                                   7
LHR to TXL                                   7
LGW to AGP                                   7
Larnaca to LHR                               7
Los Angeles to LHR                           7
New York JFK to LHR                          7
VIE to LHR                                   7
Washington to LHR                            7
LHR to Paris                                 7
LHR to Seattle                               7
AGP to LGW                                   7
PRG to LHR                                   7
LHR to NBO                                   7
LHR to FRA                                   6
LHR to Munich                                6
LGW to Orlando                               6
LGW to Mauritius                             6
St Lucia to LGW                              6
GVA to LHR                                   6
LHR to Pisa                                  6
LHR to YVR                                   6
YYZ to LHR                                   6
LHR to LAX                                   6
LHR to BOS                                   6
LHR to JTR                                   6
LAS to LHR                                   6
SFO to LHR                                   6
LHR to SYD via Singapore                     6
 LIS toLondon                                6
LHR to Washington                            6
Buenos Aires to LHR                          6
Orlando to LGW                               6
LHR to PRG                                   6
Denver to LHR                                6
GLA to LHR                                   6
Orlando to LHR                               6
LHR to IAH                                   6
LHR to GIB                                   5
Phoenix to LHR                               5
Warsaw to LHR                                5
LHR to Bologna                               5
LHR to Austin                                5
LHR to IAD                                   5
LHR to Barcelona                             5
Vancouver to LHR                             5
LHR to Venice                                5
LHR to YYC                                   5
Las Vegas to LHR                             5
KUL to LHR                                   5
Mumbai to LHR                                5
Munich to LHR                                5
LGW to AMS                                   5
DFW to LHR                                   5
LHR to NCL                                   5
LHR to Phoenix                               5
Singapore to LHR                             5
LGW to Alicante                              5
LHR to Kuala Lumpur                          5
ANU to LGW                                   5
LGW to TPA                                   5
LHR to Cairo                                 5
GIG to LHR                                   5
BGI to LGW                                   5
LHR to TPA                                   5
LGW to Funchal                               5
LHR to Budapest                              5
Beijing to LHR                               4
LGW to ANU                                   4
ICN to LHR                                   4
LGW to Pisa                                  4
LHR to DEN                                   4
ATL to LHR                                   4
PHL to LHR                                   4
LGW to PUJ                                   4
LGW to Barcelona                             4
Copenhagen to LHR                            4
DXB to LHR                                   4
LGW to MCO                                   4
LGW to UVF                                   4
SYD to LHR via SIN                           4
LHR to LAS                                   4
NCE to LHR                                   4
MXP to LHR                                   4
LCA to LHR                                   4
LHR to BUD                                   4
LHR to DFW                                   4
LHR to Milan                                 4
LHR to Shanghai                              4
CYY to LHR                                   4
Bucharest to LHR                             4
LGW to CPT                                   4
LHR to BGI                                   4
LHR to Tel Aviv                              4
Boston to LHR                                4
TPA to LGW                                   4
MRS to LHR                                   4
LHR to LYS                                   4
LYS to LHR                                   4
EDI to LGW                                   4
NRT to LHR                                   4
San Diego to LHR                             4
LHR to ICN                                   4
LHR to Mumbai                                4
LGW to Las Vegas                             4
Venice to LGW                                4
Singapore to SYD                             4
Bari to LGW                                  4
Seattle to LHR                               4
Kuala Lumpur to LHR                          4
SYD to Singapore                             4
Tokyo to LHR                                 4
Moscow to LHR                                4
SOF to LHR                                   4
ABZ to LHR                                   4
MAN to LHR                                   4
BLR to LHR                                   4
LHR to Tokyo                                 4
Amman to LHR                                 4
DUB to LHR City                              3
LGW to Venice                                3
LHR to ABZ                                   3
LHR to BCN                                   3
LHR to SYD via SIN                           3
LHR to JED                                   3
ORD to LHR                                   3
CUN to LGW                                   3
Pisa to LHR                                  3
DOH to LHR via BAH                           3
LHR to GRU                                   3
LHR to EWR                                   3
LHR to BOM                                   3
LHR to Denver                                3
Austin to LHR                                3
LGW to MRU                                   3
NBO to LHR                                   3
LHR to SEA                                   3
UVF to LGW                                   3
LHR to FAO                                   3
Atlanta to LHR                               3
LIS to LHR                                   3
BCN to LHR                                   3
LHR to Copenhagen                            3
FAO to LHR                                   3
LHR to BHD                                   3
LGW to OPO                                   3
AUH to LHR                                   3
LHR to Paris CDG                             3
LHR to LCA                                   3
NAP to LGW                                   3
LGW to RAK                                   3
LHR to MUC                                   3
LHR to CDG                                   3
EDI to LHR City                              3
LHR to Milan Malpensa                        3
Budapest to LHR                              3
LHR to Düsseldorf                            3
LHR to Philadelphia                          3
LGW to Dubrovnik                             3
LGW to St Lucia                              3
LHR to Paris Orly                            3
San Jose to LGW                              3
LHR to Montreal                              3
Naples to LGW                                3
LGW to FAO                                   3
Newark to LHR                                3
Accra to LHR                                 3
LHR to Bucharest                             3
LHR to Toulouse                              3
LGW to GLA                                   3
AMS to LGW                                   3
LGW to Marrakech                             3
LHR to Dusseldorf                            3
New Orleans to LHR                           3
LHR to Bengaluru                             3
LGW to SVQ                                   3
Bordeaux to LGW                              3
LHR to Abu Dhabi                             3
LHR toJNB                                    3
LHR to MLE                                   3
EDI to LHR                                   3
Doha to LHR                                  3
LHR to Chennai                               3
LHR to NRT                                   3
LHR to Doha                                  3
BGI to LHR                                   3
Paris to LHR                                 3
LHR to PHL                                   3
LHR to Keflavik                              3
LBA to LHR                                   3
Pisa to LGW                                  3
LHR to Chicago O'Hare                        3
LHR to Marrakech                             3
Barcelona to LHR                             3
LHR to CPH                                   3
LHR to Accra                                 3
MLA to LGW                                   3
LHR to PHX                                   3
JNB to CPT                                   3
LHR to BLR                                   3
MLE to LHR                                   2
GRU to LHR                                   2
LHR to Mexico City                           2
LHR toLas Vegas                              2
LHR to SAN                                   2
LCY to IOM                                   2
OSL to LHR                                   2
LHR to PEK                                   2
CPH to LHR                                   2
AGP to LHR                                   2
GLA to BKK via LHR                           2
YUL to FCO via LHR                           2
EDI to LAS via LHR                           2
OTP to LHR                                   2
LHR to GIG                                   2
LHR to PSA                                   2
MIA to MAN via LHR                           2
IAD to DXB via LHR                           2
LHR to AUS                                   2
LHR to EZE                                   2
IAD to LHR                                   2
Paris CDG to LHR                             2
RAK to LGW                                   2
TLV to LHR                                   2
SEA to LHR                                   2
 LIS toLHR                                   2
LGW to LIM                                   2
LHR to OTP                                   2
Tenerife to LHR                              2
GIB to LHR                                   2
DUB to LCY                                   2
LGW to ALC                                   2
LHR to Valencia                              2
SYD to SIN                                   2
LHR to CPT via JNB                           2
LHR to Reykjavik                             2
LHR to ORD                                   2
LHR to KRK                                   2
Las Vegas to LHR                             2
DUR to CPT                                   2
CPT to DUR                                   2
LHR to Tenerife                              2
LHR to KGS                                   2
LHR to ATL                                   2
BOS to LHR                                   2
DBV to LGW                                   2
LGW to MLA                                   2
HND to LHR                                   2
LHR to BRU                                   2
KWI to EDI via LHR                           2
SYD to LHR                                   2
LHR to Mauritius                             2
MAN to JFK via LHR                           2
LCY to GVA                                   2
Dubrovnik to LHR                             2
SIN to SYD                                   2
WAW to LHR                                   2
LHR to SVO                                   2
LGW to DBV                                   2
PHX to LHR                                   2
LHR-BOM                                      2
Washington Dulles to LHR                     2
LCY to JFK via SNN                           2
SSH to LGW                                   2
London City to EDI                           2
NCL to LHR                                   2
Mauritius to LGW                             2
LGW to Mauritius                             2
Malta to LGW                                 2
LGW to GOA                                   2
LGW to Grenada                               2
LHR toSFO                                    2
LHR to Athens                                2
Cairo to LHR                                 2
LHR to Beijing                               2
LGW to Salzburg                              2
GLA to LGW                                   2
LHR to FCO                                   2
MAN to LAX via LHR                           2
MAN to LAS via LHR                           2
BUD to LHR                                   2
CDG to BKK via LHR                           2
LHR to HAM                                   2
Milan to LHR                                 2
LHR to Warsaw                                2
Barcelona to LGW                             2
LHR to Sao Paulo                             2
LHR to Marrakesh                             2
LHR to HEL                                   2
LHR to Moscow                                2
LGW to Tirana                                2
NBO to New York via London                   2
TXL to LHR City                              2
Tokyo Haneda to LHR                          2
LHR to Basel                                 2
Bologna to LHR                               2
LGW to Rome Fiumicino                        2
Reykjavik to LHR                             2
Salzburg to LGW                              2
LGW to Bari                                  2
Tel Aviv to LHR                              2
CDG to LHR                                   2
SVQ to LGW                                   2
LHR to Santiago de Chile                     2
Seychelles to LHR                            2
FAO to LGW                                   2
LHR to Stuttgart                             2
Heraklion to LGW                             2
HAM to LHR                                   2
LGW to Paphos                                2
ZAG to LHR                                   2
Baltimore to LHR                             2
Toulouse to LHR                              2
LHR to JNB                                   2
Brussels to LHR                              2
Mexico City to LHR                           2
LHR to Buenos Aires                          2
Stuttgart to LHR                             2
LHR toVancouver                              2
JED to LHR                                   2
LHR to Jersey                                2
GLA to New York via London                   2
Abu Dhabi to LHR                             2
LHR to Chicago                               2
IAH to LHR                                   2
LHR to CYY                                   2
LHR to Tokyo Haneda                          2
JNB to LHR                                   2
LHR to TXL Tegel                             2
BDA to LGW                                   2
Lima to LGW                                  2
LHR toSingapore                              2
LGW to Tenerife                              2
Keflavik to LHR                              2
LHR to Gothenburg                            2
LHR to St Petersburgh                        2
LGW to Cagliari                              2
Chennai to LHR                               2
LGW to BDA                                   2
HAM to Abu Dhabi via LHR                     2
Mykonos to LHR                               2
 RTM toLondon City                           2
LGW to San Jose Costa Rica                   2
LHR to Kalamata                              2
London City to IBZ                           2
LHR to Amman                                 2
LHR toBrussels                               1
BOM-LHR                                      1
LHR to BJV                                   1
Tel Aviv to LHR LHR                          1
DME to GLA via LHR                           1
GLA to DME via LGW / LHR                     1
Bologna to Montreal via London               1
DUB to Vancouver via LHR                     1
São Paulo to Milan via London                1
Dubai to Milan Malpensa via London           1

In [82]:
heathrow_routes = df[df['Route'].str.contains('St Lucia', case=False, na=False)]
display(heathrow_routes['Route'].value_counts())

Route
St Lucia to LGW                6
LGW to St Lucia                3
LHR to St Lucia                1
AMS to St Lucia via Gatwick    1
Name: count, dtype: int64

In [66]:
with pd.option_context('display.max_rows', None):
    display(heathrow_routes['Route'].value_counts())

Route
LHR to Delhi                     7
Vancouver to Delhi via London    1
NCL to Delhi via London          1
MIA to Delhi via LHR             1
Delhi to LHR                     1
LHR to Delhi Airport             1
LHR to New Delhi                 1
Name: count, dtype: int64

In [19]:
heathrow_routes.head(30)

,Passanger_Name,Route,Rating,Review_title,Review_content,Start_Location,End_Location,Layover_Route,Start_Address,End_Address,Class_Business Class,Class_Economy Class,Class_First Class,Class_Premium Economy,Traveller_Type_Business,Traveller_Type_Couple Leisure,Traveller_Type_Family Leisure,Traveller_Type_Solo Leisure,Verified_Trip Verified,Satisfied
99,M Kaminsky,New York to Istanbul via London,10.0,Would happily fly them again,Would happily fly them again. I had a personal...,New York,Istanbul,London,"City of New York, New York, United States","İstanbul, Marmara Bölgesi, Türkiye",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1
131,Hans Book,Istanbul to Vancouver via LHR,1.0,Luggage is delayed,"The staff are friendly. The plane was cold, we...",Istanbul,Vancouver,Heathrow,"İstanbul, Marmara Bölgesi, Türkiye","Vancouver, Metro Vancouver Regional District, ...",0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
189,L Tran,Istanbul to LHR,3.0,I still found it underwhelming,The check-in process was smooth. I got access ...,Istanbul,London Heathrow,None,"İstanbul, Marmara Bölgesi, Türkiye","London Heathrow Airport, Northern Perimeter Ro...",1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
196,Shahid Habib,London to Istanbul,1.0,very short leg space,London to Istanbul. British Airways Business C...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
353,James Goldie,London to Istanbul,2.0,BA hang your head in shame,I had low expectations of business class BA on...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
534,R Easson,Istanbul to London,3.0,BA product is now tired,Istanbul to London. We had to wait for ages to...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
618,A Allam,Istanbul to New York via London,1.0,first and definitely last time,Istanbul to New York via London. Literally the...,Istanbul,New York,London,"İstanbul, Marmara Bölgesi, Türkiye","City of New York, New York, United States",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
640,S Hasima,Los Angeles to Istanbul via London,4.0,wanted to change our departure date,Los Angeles to Istanbul via London. Flight bet...,Los Angeles,Istanbul,London,"Los Angeles, Los Angeles County, California, U...","İstanbul, Marmara Bölgesi, Türkiye",1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
731,Ally Wharton,Istanbul to London,5.0,the cabin crew were great,Istanbul to London. My first flight in Economy...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1
1003,Matt Beks,Istanbul to LHR,1.0,need to improve service levels,Istanbul to London Heathrow. The plane itself ...,Istanbul,London Heathrow,None,"İstanbul, Marmara Bölgesi, Türkiye","London Heathrow Airport, Northern Perimeter Ro...",0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
1025,Colin Lewis,London to Istanbul,2.0,gate staff should be better trained,Flew to Istanbul with British Airways on 5th J...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1066,V Caulsen,London to Istanbul,1.0,nearly three hours late,London to Istanbul. Due to poor weather condit...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0
1118,M Owen,Istanbul to London,2.0,it’s become a last resort,BA used to be a byword for quality and service...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
1163,W Upson,London to Istanbul,1.0,a miserable experience,London to Istanbul. Flying in BA's Club Europe...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1328,A Madek,LHR to Istanbul,2.0,is quite clearly in decline,Verified Review London Heathrow to Istanbul....,London Heathrow,Istanbul,None,"London Heathrow Airport, The Beacon Roundabout...","İstanbul, Marmara Bölgesi, Türkiye",0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
1362,Kemal Giray,Istanbul to London,1.0,become a budget airline,Verified Review I had a return flight to Ist...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
1488,Greg Penola,Istanbul to London,3.0,like a low cost carrier,Verified Review Istanbul to London on a reas...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
1580,C Walton,Istanbul to London,1.0,little more than a budget airline,Verified Review Istanbul to London. I am sad...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1638,S Lepinski,London to Istanbul,1.0,my last time to book with them,Verified Review This will be my last time to...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1686,S Hanylu,Istanbul to London,3.0,the worst airline so far,Verified Review Istanbul to London Heathrow....,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2469,A Long,Istanbul to London,1.0,no space to work,I would never fly British Airways on London-Is...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
2597,Julie Green,Istanbul to Denver via LHR,1.0,I will avoid British Airways in the future,I am so upset with British Airways that I will...,Istanbul,Denver,London - Heathrow,"İstanbul, Marmara Bölgesi, Türkiye","Denver, Colorado, United States",1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2713,Bob Motto,LHR to Istanbul,9.0,British Airways customer review,"Flew Club Europe to Istanul on 767, boarding w...",London Heathrow,Istanbul,None,"London Heathrow Airport, The Beacon Roundabout...","İstanbul, Marmara Bölgesi, Türkiye",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
2747,Andrew Ray,Istanbul to London,3.0,British Airways customer review,Same tired plane back to London. Ground and ca...,Istanbul,London,None,"İstanbul, Marmara Bölgesi, Türkiye","London, Greater London, England, United Kingdom",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
2751,A Ray,London to Istanbul,1.0,British Airways customer review,Expected Club world got Club Europe - the same...,London,Istanbul,None,"London, Greater London, England, United Kingdom","İstanbul, Marmara Bölgesi, Türkiye",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0