# CLEANING FOR CUSTOMER_COMMENT & SURVEY & PASSANGER TABLES

In [2]:
import pandas as pd
import os

# Read the CSV files with correct file names
cc = pd.read_csv("../Customer_comment.csv")
sd = pd.read_csv("../Survey data_Inflight Satisfaction Score.csv")
pb = pd.read_csv("../Passanger_booking_data.csv")

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
cc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9424 entries, 0 to 9423
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                9424 non-null   int64
 1   flight_number             9424 non-null   int64
 2   origin_station_code       9424 non-null   object
 3   destination_station_code  9424 non-null   object
 4   scheduled_departure_date  9424 non-null   object
 5   arrival_delay_group       9424 non-null   object
 6   departure_delay_group     9424 non-null   object
 7   entity                    9424 non-null   object
 8   verbatim_text             9424 non-null   object
 9   seat_factor_band          9424 non-null   object
 10  ques_verbatim_text        9424 non-null   object
 11  loyalty_program_level     6920 non-null   object
 12  fleet_type_description    9424 non-null   object
 13  fleet_usage               9424 non-null   object
 14  response_group            9424 non-null   object
 15  sentiments                9424 non-null   object
 16  transformed_text          8405 non-null   object
dtypes: int64(2), object(15)
memory usage: 1.2+ MB

In [5]:
cc.describe()

        Unnamed: 0  flight_number
count  9424.000000    9424.000000
mean   4711.500000    1741.573430
std    2720.618802    1550.550037
min       0.000000       2.000000
25%    2355.750000     614.000000
50%    4711.500000    1286.000000
75%    7067.250000    2261.000000
max    9423.000000    6375.000000

In [6]:
cc.describe(include=['object'])

,origin_station_code,destination_station_code,scheduled_departure_date,arrival_delay_group,departure_delay_group,entity,verbatim_text,seat_factor_band,ques_verbatim_text,loyalty_program_level,fleet_type_description,fleet_usage,response_group,sentiments,transformed_text
count,9424,9424,9424,9424,9424,9424,9424,9424,9424,6920,9424,9424,9424,9424,8405
unique,195,192,30,2,2,4,8013,4,1,7,22,2,3,2,7609
top,IAX,IAX,2022-09-10,Early & Ontime,Early & Ontime,Domestic,No.,90+,Is there anything else you'd like to share abo...,non-elite,B737-900,Mainline,member,Neutral,none
freq,1149,1427,399,6811,6241,6593,774,6302,9424,4128,1451,7985,6905,9307,97

In [7]:
cc.isnull().sum()

Unnamed: 0                     0
flight_number                  0
origin_station_code            0
destination_station_code       0
scheduled_departure_date       0
arrival_delay_group            0
departure_delay_group          0
entity                         0
verbatim_text                  0
seat_factor_band               0
ques_verbatim_text             0
loyalty_program_level       2504
fleet_type_description         0
fleet_usage                    0
response_group                 0
sentiments                     0
transformed_text            1019
dtype: int64

In [8]:
cc["loyalty_program_level"].value_counts()

loyalty_program_level
non-elite           4128
premier silver       874
premier 1k           722
premier gold         604
premier platinum     451
global services      140
NBK                    1
Name: count, dtype: int64

In [9]:
# Drop rows where loyalty_program_level is 'nbk' since there is only one occurrence
cc = cc[cc["loyalty_program_level"] != "NBK"]
cc["loyalty_program_level"].value_counts()

loyalty_program_level
non-elite           4128
premier silver       874
premier 1k           722
premier gold         604
premier platinum     451
global services      140
Name: count, dtype: int64

In [10]:
# Fill null values in loyalty_program_level with "No Program" 
# since normally you have to enroll to a loyalty program manually 
# so assume they are not in one
cc["loyalty_program_level"].fillna("No Program", inplace=True)
print(cc["loyalty_program_level"].value_counts())

loyalty_program_level
non-elite           4128
No Program          2504
premier silver       874
premier 1k           722
premier gold         604
premier platinum     451
global services      140
Name: count, dtype: int64

C:\Users\Omar-Harridy\AppData\Local\Temp\ipykernel_9312\3278579344.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cc["loyalty_program_level"].fillna("No Program", inplace=True)

In [11]:
cc["transformed_text"].fillna("No Comment", inplace=True)
cc.isnull().sum()
#end customer comment data cleaning

C:\Users\Omar-Harridy\AppData\Local\Temp\ipykernel_9312\2843024592.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cc["transformed_text"].fillna("No Comment", inplace=True)

Unnamed: 0                  0
flight_number               0
origin_station_code         0
destination_station_code    0
scheduled_departure_date    0
arrival_delay_group         0
departure_delay_group       0
entity                      0
verbatim_text               0
seat_factor_band            0
ques_verbatim_text          0
loyalty_program_level       0
fleet_type_description      0
fleet_usage                 0
response_group              0
sentiments                  0
transformed_text            0
dtype: int64

In [12]:
pb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50002 entries, 0 to 50001
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   num_passengers         50002 non-null  int64
 1   sales_channel          50002 non-null  object
 2   trip_type              50002 non-null  object
 3   purchase_lead          50002 non-null  int64
 4   length_of_stay         50002 non-null  int64
 5   flight_hour            50002 non-null  int64
 6   flight_day             50002 non-null  object
 7   route                  50002 non-null  object
 8   booking_origin         50002 non-null  object
 9   wants_extra_baggage    50002 non-null  int64
 10  wants_preferred_seat   50002 non-null  int64
 11  wants_in_flight_meals  50002 non-null  int64
 12  flight_duration        50002 non-null  float64
 13  booking_complete       50002 non-null  int64
dtypes: float64(1), int64(8), object(5)
memory usage: 5.3+ MB

In [13]:
pb.describe()

,num_passengers,purchase_lead,length_of_stay,flight_hour,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
count,50002.000000,50002.000000,50002.000000,50002.000000,50002.000000,50002.000000,50002.000000,50002.000000,50002.000000
mean,1.591256,84.940582,23.044778,9.066277,0.668773,0.296968,0.427143,7.277524,0.149574
std,1.020167,90.450548,33.887171,5.412569,0.470659,0.456927,0.494668,1.496854,0.356657
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.670000,0.000000
25%,1.000000,21.000000,5.000000,5.000000,0.000000,0.000000,0.000000,5.620000,0.000000
50%,1.000000,51.000000,17.000000,9.000000,1.000000,0.000000,0.000000,7.570000,0.000000
75%,2.000000,115.000000,28.000000,13.000000,1.000000,1.000000,1.000000,8.830000,0.000000
max,9.000000,867.000000,778.000000,23.000000,1.000000,1.000000,1.000000,9.500000,1.000000

In [14]:
pb.describe(include=['object'])

       sales_channel  trip_type flight_day   route booking_origin
count          50002      50002      50002   50002          50002
unique             2          3          7     799            104
top         Internet  RoundTrip        Mon  AKLKUL      Australia
freq           44383      49498       8102    2680          17873

In [15]:
duplicatespb = pb[pb.duplicated()]
duplicatespb.shape

(719, 14)

In [16]:
# Remove duplicates
pb=pb.drop_duplicates()
pb.shape
#end passanger booking data cleaning since no nulls

(49283, 14)

In [17]:
sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47074 entries, 0 to 47073
Data columns (total 31 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   flight_number                     47074 non-null  int64
 1   origin_station_code               47074 non-null  object
 2   destination_station_code          47074 non-null  object
 3   record_locator                    47074 non-null  object
 4   scheduled_departure_date          47074 non-null  object
 5   question_text                     47074 non-null  object
 6   score                             47074 non-null  object
 7   satisfaction_type                 34963 non-null  object
 8   driver_sub_group1                 47074 non-null  object
 9   driver_sub_group2                 47074 non-null  object
 10  arrival_delay_minutes             47074 non-null  int64
 11  arrival_delay_group               47074 non-null  object
 12  cabin_code_desc                   47074 non-null  object
 13  cabin_name                        27094 non-null  object
 14  entity                            47071 non-null  object
 15  number_of_legs                    47074 non-null  int64
 16  seat_factor_band                  47074 non-null  object
 17  loyalty_program_level             35458 non-null  object
 18  generation                        47074 non-null  object
 19  fleet_type_description            47074 non-null  object
 20  fleet_usage                       47074 non-null  object
 21  equipment_type_code               47074 non-null  object
 22  ua_uax                            47074 non-null  object
 23  actual_flown_miles                47074 non-null  int64
 24  haul_type                         47074 non-null  object
 25  departure_gate                    46977 non-null  object
 26  arrival_gate                      46547 non-null  object
 27  international_domestic_indicator  47074 non-null  object
 28  response_group                    47074 non-null  object
 29  media_provider                    45535 non-null  object
 30  hub_spoke                         47074 non-null  object
dtypes: int64(4), object(27)
memory usage: 11.1+ MB

In [18]:
sd.describe()

,flight_number,arrival_delay_minutes,number_of_legs,actual_flown_miles
count,47074.000000,47074.000000,47074.000000,47074.000000
mean,1529.855207,-1.702490,1.344118,2477.737732
std,1456.712299,37.868177,0.502424,1865.646538
min,2.000000,-104.000000,1.000000,45.000000
25%,477.000000,-19.000000,1.000000,932.000000
50%,1050.000000,-9.000000,1.000000,1846.000000
75%,2060.000000,4.000000,2.000000,3870.000000
max,6376.000000,907.000000,3.000000,8440.000000

In [19]:
sd.describe(include=['object'])

,origin_station_code,destination_station_code,record_locator,scheduled_departure_date,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,arrival_delay_group,...,fleet_usage,equipment_type_code,ua_uax,haul_type,departure_gate,arrival_gate,international_domestic_indicator,response_group,media_provider,hub_spoke
count,47074,47074,47074,47074,47074,47074,34963,47074,47074,47074,...,47074,47074,47074,47074,46977,46547,47074,47074,45535,47074
unique,213,212,33095,30,2,12,2,1,2,2,...,2,40,2,3,656,692,2,3,4,2
top,IAX,EWX,JNXXVS,9/10/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,Early & Ontime,...,Mainline,37K,UA,Medium,A8,HOLD,Domestic,member,PANASONIC,hub departure
freq,5758,7058,6,1872,34963,8250,22353,47074,34963,32868,...,41628,6366,41628,26423,589,965,29242,35382,24979,24343

In [20]:
# Set pandas display options to show all rows
pd.set_option('display.max_rows', None)

# Display null counts
print(sd.isnull().sum())

# Optionally reset display options back to default
pd.reset_option('display.max_rows')

flight_number                           0
origin_station_code                     0
destination_station_code                0
record_locator                          0
scheduled_departure_date                0
question_text                           0
score                                   0
satisfaction_type                   12111
driver_sub_group1                       0
driver_sub_group2                       0
arrival_delay_minutes                   0
arrival_delay_group                     0
cabin_code_desc                         0
cabin_name                          19980
entity                                  3
number_of_legs                          0
seat_factor_band                        0
loyalty_program_level               11616
generation                              0
fleet_type_description                  0
fleet_usage                             0
equipment_type_code                     0
ua_uax                                  0
actual_flown_miles                      0
haul_type                               0
departure_gate                         97
arrival_gate                          527
international_domestic_indicator        0
response_group                          0
media_provider                       1539
hub_spoke                               0
dtype: int64

In [21]:
sd['media_provider'].value_counts()

media_provider
PANASONIC    24979
THALES       12765
GOGO          3907
VIASAT        3884
Name: count, dtype: int64

In [22]:
sd["media_provider"].fillna("No Media", inplace=True)

C:\Users\Omar-Harridy\AppData\Local\Temp\ipykernel_9312\210854833.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sd["media_provider"].fillna("No Media", inplace=True)

In [23]:
sd['arrival_gate'].value_counts()

arrival_gate
HOLD    965
B55     480
A8      443
C5      435
C3      434
       ...
89        1
A5F       1
A3E       1
410       1
-2-       1
Name: count, Length: 692, dtype: int64

In [24]:

sd=sd.dropna(subset=['arrival_gate'])

In [25]:
sd.isnull().sum()

flight_number                           0
origin_station_code                     0
destination_station_code                0
record_locator                          0
scheduled_departure_date                0
question_text                           0
score                                   0
satisfaction_type                   12098
driver_sub_group1                       0
driver_sub_group2                       0
arrival_delay_minutes                   0
arrival_delay_group                     0
cabin_code_desc                         0
cabin_name                          19899
entity                                  3
number_of_legs                          0
seat_factor_band                        0
loyalty_program_level               11452
generation                              0
fleet_type_description                  0
fleet_usage                             0
equipment_type_code                     0
ua_uax                                  0
actual_flown_miles                      0
haul_type                               0
departure_gate                         96
arrival_gate                            0
international_domestic_indicator        0
response_group                          0
media_provider                          0
hub_spoke                               0
dtype: int64

In [26]:
sd=sd.dropna(subset=['departure_gate'])

In [27]:
sd["loyalty_program_level"].value_counts()

loyalty_program_level
non-elite           19041
premier silver       4803
premier 1k           4305
premier gold         3329
premier platinum     2616
global services       930
NBK                     3
Name: count, dtype: int64

In [28]:
# Drop rows where loyalty_program_level is 'nbk' since there is only 3 occurrence
sd = sd[sd["loyalty_program_level"] != "NBK"]

# Fill null values in loyalty_program_level with "No Program" 
# since normally you have to enroll to a loyalty program manually 
# so assume they are not in one
sd["loyalty_program_level"].fillna("No Program", inplace=True)
sd["loyalty_program_level"].value_counts()

C:\Users\Omar-Harridy\AppData\Local\Temp\ipykernel_9312\768702302.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sd["loyalty_program_level"].fillna("No Program", inplace=True)

loyalty_program_level
non-elite           19041
No Program          11424
premier silver       4803
premier 1k           4305
premier gold         3329
premier platinum     2616
global services       930
Name: count, dtype: int64

In [29]:
sd.isnull().sum()

flight_number                           0
origin_station_code                     0
destination_station_code                0
record_locator                          0
scheduled_departure_date                0
question_text                           0
score                                   0
satisfaction_type                   12094
driver_sub_group1                       0
driver_sub_group2                       0
arrival_delay_minutes                   0
arrival_delay_group                     0
cabin_code_desc                         0
cabin_name                          19888
entity                                  3
number_of_legs                          0
seat_factor_band                        0
loyalty_program_level                   0
generation                              0
fleet_type_description                  0
fleet_usage                             0
equipment_type_code                     0
ua_uax                                  0
actual_flown_miles                      0
haul_type                               0
departure_gate                          0
arrival_gate                            0
international_domestic_indicator        0
response_group                          0
media_provider                          0
hub_spoke                               0
dtype: int64

In [30]:
sd['entity'].value_counts()

entity
Domestic    28625
Atlantic    12904
Latin        3371
Pacific      1545
Name: count, dtype: int64

In [31]:
sd.head(5)

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,...,equipment_type_code,ua_uax,actual_flown_miles,haul_type,departure_gate,arrival_gate,international_domestic_indicator,response_group,media_provider,hub_spoke
0,3802,MKX,ORX,CYXXJJ,9/1/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,...,CRZ,UAX,67,Short,C12,F10,Domestic,non-member,No Media,spoke departure
1,4645,COX,DEX,DRXXMH,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,E75,UAX,72,Short,5,B60,Domestic,member,GOGO,spoke departure
2,5236,COX,DEX,DEXXS1,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,E75,UAX,72,Short,7,A71,Domestic,member,GOGO,spoke departure
3,4686,DEX,COX,PXXXLH,9/1/2022,How satisfied were you with the food & beverag...,3,Dissatisfied,food & beverage,food and beverage satisfaction,...,CRJ,UAX,72,Short,B82,5,Domestic,member,No Media,hub departure
4,671,DEX,COX,KZXXH5,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,...,19F,UA,72,Short,B24,3,Domestic,member,PANASONIC,hub departure

In [32]:
sd[sd["entity"].isna()]

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,...,equipment_type_code,ua_uax,actual_flown_miles,haul_type,departure_gate,arrival_gate,international_domestic_indicator,response_group,media_provider,hub_spoke
39948,3020,SJX,PTX,A3XX7C,9/26/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,37K,UA,335,Short,8,137,International,member,VIASAT,spoke departure
39949,3020,SJX,PTX,AFXX8Y,9/26/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,37K,UA,335,Short,8,137,International,member,VIASAT,spoke departure
39950,3020,SJX,PTX,A5XX47,9/26/2022,How satisfied were you with the food & beverag...,1,Dissatisfied,food & beverage,food and beverage satisfaction,...,37K,UA,335,Short,8,137,International,member,VIASAT,spoke departure

In [33]:
#because this these flight departure from a city in Latin America so entity is Latin
sd["entity"].fillna("Latin", inplace=True)

C:\Users\Omar-Harridy\AppData\Local\Temp\ipykernel_9312\3433507448.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sd["entity"].fillna("Latin", inplace=True)

In [34]:
sd["cabin_code_desc"].value_counts()

cabin_code_desc
Economy                26560
Business               17926
United Premium Plus     1962
Name: count, dtype: int64

In [35]:
sd["cabin_name"].value_counts()

cabin_name
Economy         17968
Economy Plus     8592
Name: count, dtype: int64

In [36]:
# Merged columns since it doesnt make sense to have two columns for cabin class 
sd['cabin_name'] = sd['cabin_name'].fillna(sd['cabin_code_desc'])
sd = sd.drop(columns=['cabin_code_desc'])
sd = sd.rename(columns={'cabin_name': 'cabin_class'})

In [37]:
sd["cabin_class"].value_counts()

cabin_class
Economy                17968
Business               17926
Economy Plus            8592
United Premium Plus     1962
Name: count, dtype: int64

In [38]:
sd.isnull().sum()

flight_number                           0
origin_station_code                     0
destination_station_code                0
record_locator                          0
scheduled_departure_date                0
question_text                           0
score                                   0
satisfaction_type                   12094
driver_sub_group1                       0
driver_sub_group2                       0
arrival_delay_minutes                   0
arrival_delay_group                     0
cabin_class                             0
entity                                  0
number_of_legs                          0
seat_factor_band                        0
loyalty_program_level                   0
generation                              0
fleet_type_description                  0
fleet_usage                             0
equipment_type_code                     0
ua_uax                                  0
actual_flown_miles                      0
haul_type                               0
departure_gate                          0
arrival_gate                            0
international_domestic_indicator        0
response_group                          0
media_provider                          0
hub_spoke                               0
dtype: int64

In [39]:
sd["satisfaction_type"].value_counts()

satisfaction_type
Dissatisfied    21977
Satisfied       12377
Name: count, dtype: int64

In [40]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
sd.head(5)

,flight_number,origin_station_code,destination_station_code,record_locator,scheduled_departure_date,question_text,score,satisfaction_type,driver_sub_group1,driver_sub_group2,arrival_delay_minutes,arrival_delay_group,cabin_class,entity,number_of_legs,seat_factor_band,loyalty_program_level,generation,fleet_type_description,fleet_usage,equipment_type_code,ua_uax,actual_flown_miles,haul_type,departure_gate,arrival_gate,international_domestic_indicator,response_group,media_provider,hub_spoke
0,3802,MKX,ORX,CYXXJJ,9/1/2022,How satisfied were you with the food & beverag...,2,Dissatisfied,food & beverage,food and beverage satisfaction,-24,Early & Ontime,Economy,Domestic,2,80+,No Program,Gen X,CRJ-200,Express,CRZ,UAX,67,Short,C12,F10,Domestic,non-member,No Media,spoke departure
1,4645,COX,DEX,DRXXMH,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,10,Delayed,Business,Domestic,2,90+,premier platinum,Boomer,ERJ-175,Express,E75,UAX,72,Short,5,B60,Domestic,member,GOGO,spoke departure
2,5236,COX,DEX,DEXXS1,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,-8,Early & Ontime,Business,Domestic,2,90+,premier platinum,Gen X,ERJ-175,Express,E75,UAX,72,Short,7,A71,Domestic,member,GOGO,spoke departure
3,4686,DEX,COX,PXXXLH,9/1/2022,How satisfied were you with the food & beverag...,3,Dissatisfied,food & beverage,food and beverage satisfaction,-11,Early & Ontime,Economy,Domestic,3,90+,non-elite,Boomer,CRJ-200,Express,CRJ,UAX,72,Short,B82,5,Domestic,member,No Media,hub departure
4,671,DEX,COX,KZXXH5,9/1/2022,How satisfied were you with the food & beverag...,5,Satisfied,food & beverage,food and beverage satisfaction,18,Delayed,Business,Domestic,2,90+,premier silver,Boomer,A319-100,Mainline,19F,UA,72,Short,B24,3,Domestic,member,PANASONIC,hub departure

In [ ]:
# The trend in the rows is that satisfaction type is dependent on the score
# so if score is 4 or 5 we can use this to fill in the missing values
mask = sd["satisfaction_type"].isna()
sd.loc[mask, "satisfaction_type"] = np.where(
    (sd.loc[mask, "score"] == "4") | (sd.loc[mask, "score"] == "5"),
    "Satisfied",
    "Dissatisfied"
)

In [52]:
sd.isnull().sum()

flight_number                       0
origin_station_code                 0
destination_station_code            0
record_locator                      0
scheduled_departure_date            0
question_text                       0
score                               0
satisfaction_type                   0
driver_sub_group1                   0
driver_sub_group2                   0
arrival_delay_minutes               0
arrival_delay_group                 0
cabin_class                         0
entity                              0
number_of_legs                      0
seat_factor_band                    0
loyalty_program_level               0
generation                          0
fleet_type_description              0
fleet_usage                         0
equipment_type_code                 0
ua_uax                              0
actual_flown_miles                  0
haul_type                           0
departure_gate                      0
arrival_gate                        0
international_domestic_indicator    0
response_group                      0
media_provider                      0
hub_spoke                           0
dtype: int64

In [53]:
print(sd.shape)
sd=sd.drop_duplicates()
print(sd.shape)

(46448, 30)
(46448, 30)